id: P88D5C022
initial_creation_type: input
source_metadata:
  title: Jokyab Pema Trinlé Nyingpo
  language: en
  description: 'Texts by and about Jokyab Pema Trinlé Nyingpo (jo skyabs pad+ma ''phrin
    las snying po, 1903–1960):'
  volume:
    9b3c1b87c43445a08c73acec8ec5bcea:
      title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
      parent: Guru Yoga
    03b4a056e3f2476f902de999b767a232:
      title: 'A Drop of Moonlight: A Guru Yoga for Lord Mila'
      parent: Guru Yoga
    531e09978e7847b9a3b6f440e4aa2894:
      title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
      parent: Guru Yoga
    4e1491a15573483aa9387b6d9673218a:
      title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the
        Three Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
      parent: Guru Yoga
    c75c654fc6d74cac88cb1c62136183d2:
      title: Words of Jamyang Khyentse
      parent: Prayers
created_at: '2022-03-01T00:08:57.308533'
last_modified_at: '2022-03-01T00:08:57.308539'
